# Site settings
title: HUISSTIJLGIDS
email: your-email@domain.com
url:  https://gdmgent-1718-3cmo.github.io/1718-3CMO-BaP-julidecl1/
description: "ENKELE GUIDLINES VOOR ZOWEL DE OFFLINE <br>ALS ONLINE COMMUNICATIE"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
  links: '#e8424f'

# Footer settings
footer: Julie De Clercq

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
